Job order style multi file upload for repositories and project proposals
uOttawa-Makerspace/MakerSpaceRepo pull request #1258
Opened 2022-09-01 14:41 UTC by NomadNaomie

2022-09-01 18:45 UTC, art29 requested changes
Mostly good! Only issue is with the Drag & Drop, it goes under, which looks odd. If possible, try to add them over instead of under the Drag & Drop field.

2022-09-01 18:57 UTC, NomadNaomie commented
I can't add it under the drag and drop unfortunately, we can take out the drag and drop but this is what it looks like
![image](https://user-images.githubusercontent.com/89711830/187991580-c5699407-4d60-48ae-b502-fa0db8c73413.png)

2022-09-05 18:51 UTC, art29 commented on app/controllers/repositories_controller.rb
> +    puts "repository_params: #{repository_params}"
Probably remove that

2022-09-05 18:52 UTC, art29 approved these changes
You forgot a few debugging things, other than that, it's all good!

2022-09-05 18:52 UTC, art29 commented on app/javascript/packs/application.js
> +  console.log(event.dataTransfer.items);
Probably remove the console.log

2022-09-06 19:58 UTC, merged